### ISSUE TITLE
Pretty format timestamps in router logs

### ISSUE THREAD

**Issue by APShirley** [cloudfoundry-incubator/routing-release#46]
Currently timestamps for the gorouter logs appear to be formatted in epoch time, this is mildly inconvenient for humans as we have to go and convert the timestamps. It would be nice to have them formatted in ISO 8601 notation as that is both easily parseable by computers and humans alike.

Most CF components use this format.

**Comment by shalako** [comment]
Hello,
Currently gorouter.log includes messages with both timestamp formats:
```
{"timestamp":"1469578199.066300869","source":"vcap.gorouter","message":"vcap.gorouter.proxy.request-handler.handling-websocket-request","log_level":1,"data":{"Host":"doppler.superman.cf-app.com:4443","Path":"/apps/6a64c663-651f-4cd2-8994-d31d4f381704/stream","RemoteAddr":"52.3.107.171:45270","Upgrade":"websocket","X-Forwarded-For":null,"X-Forwarded-Proto":null,"session":"4.149178"}}
[2016-07-27 00:09:59+0000] {timestamp:1469578199.066300869,source:vcap.gorouter,message:vcap.gorouter.proxy.request-handler.handling-websocket-request,log_level:1,data:{Host:doppler.superman.cf-app.com:4443,Path:/apps/6a64c663-651f-4cd2-8994-d31d4f381704/stream,RemoteAddr:52.3.107.171:45270,Upgrade:websocket,X-Forwarded-For:null,X-Forwarded-Proto:null,session:4.149178}}
```

It appears that we have duplicate log messages (one message uses both ISO 8601 and epoch). We consider this a bug and will fix this. 

It is also strange that we're using both timestamp formats in one message. We'll probably pick one and remove the other. In terms of which timestamp format we'll use, it is not clear to me that there is a convention in CF currently; cloud_controller uses epoch.

```
{"timestamp":1469579302.272368,"message":"Statsd: cc.requests.outstanding:-1|c\ncc.requests.completed:1|c\ncc.http_status.2XX:1|c","log_level":"debug","source":"statsd.client","data":{},"thread_id":47367051452260,"fiber_id":47367032802760,"process_id":5497,"file":"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/statsd-ruby-1.2.1/lib/statsd.rb","lineno":254,"method":"send_to_socket"}
```

**Comment by shalako** [comment]
We have a story to dedup our logs here: https://www.pivotaltracker.com/story/show/127119107

As a result we may only use an epoch timestamp for some period. We have requested that the `lager` library we use support the ISO 8601 timestamp; when that lib is updated you'll see human readable gorouter logs.

**Comment by aaronshurley** [comment]
@APShirley : Closing this PR because we have removed duplicate log msg with non-human readable timestamps. 

Regards
Aaron && @shashwathi
