### ISSUE TITLE
CF does not recover from full shut down due to route_registrar

### ISSUE THREAD

**Issue by Amit-PivotalLabs** [cloudfoundry-incubator/routing-release#50]
This issue was originally raised [here](https://github.com/cloudfoundry/cf-release/issues/1055).

The `mkdir -p ${RUN_DIR}` should probably be done in both `pre-start` and in whatever `monit start route_registrar` invokes.

This is an issue for recovery from an unplanned full stop, and perhaps also for intentional stops and starts. /cc @cppforlife @mkocher @dsboulder 

Thanks to @neilhwatson for originally reporting this issue.

**Comment by shalako** [comment]
Prioritized

**Comment by shashwathi** [comment]
Hi @neilhwatson, 

Thank you for raising this issue. As @Amit-PivotalLabs already pointed out, it is because creating directories in pre-start and not in ctl script. This has been fixed and it will be available in Cf-release soon.

Regards
Shash

**Comment by shalako** [comment]
Verified route_registrar starts when `/var/vcap/sys/run/route_registrar` is not present, as it will create the dir on start.

The fix is in cf-release v245
