### ISSUE TITLE
Status endpoint only enabled if status.user and status.password specified

### ISSUE THREAD

**Issue by youngm** [cloudfoundry-incubator/routing-release#52]
It also appears that status.user and status.password are not actually used to get status anymore.

**Comment by shalako** [comment]
`router.status.user` and `router.status.password` should be required properties to secure the `/routes` endpoint. If that endpoint is no longer secured it may have been a regression introduced when we add the `/health` endpoint, which is meant to be open.

Prioritizing for engineering review.

**Comment by youngm** [comment]
Ah, I don't know anything about `/routes`.  So, it may still work to secure `/routes`.  In that case the question may be why do I need to specify status.user and status.password in order for gorouter to listen on `/health`?

**Comment by youngm** [comment]
I just confirmed /routes does work with the user and password provided.  I didn't know /routes existed and was confused that I needed to provide a user and password to use it.  So, you can probably close this.

**Comment by shalako** [comment]
Got it. 

See https://github.com/cloudfoundry/gorouter/#instrumentation

`status` is a poor property name when the endpoints it secures are `/varz` and `/routes`. I see the job spec descriptions for the `status` properties could be improved. Will do so.

If you have suggestions for what could be improved in docs, etc to have made the solution more self-discoverable, let us know.
