### ISSUE TITLE
hard-wired endpoints and ports in specs need to be configurable

### ISSUE THREAD

**Issue by ericpromislow** [cloudfoundry-incubator/routing-release#53]
https://github.com/cloudfoundry-incubator/routing-release/blob/74bb5adc658d0df6104d6fe2ba747254b2ab0d46/jobs/router_configurer/templates/router_configurer.yml.erb#L12-L13 and https://github.com/cloudfoundry-incubator/routing-release/blob/74bb5adc658d0df6104d6fe2ba747254b2ab0d46/jobs/tcp_emitter/templates/tcp_emitter.yml.erb#L11-L12 hardwire the endpoint for the routing-api service. 

These values should be added to the jobs' respective specs, and the constant values replaced with ERB references to the properties.

**Comment by shalako** [comment]
Hello @ericpromislow 
You've provided implementation instructions without describing user experience and use cases.

I'm guessing that you're looking for has already been submitted as a PR here: https://github.com/cloudfoundry-incubator/routing-release/pull/31. Is that right?
We're trying to get to review of that PR asap but are really short staffed at the moment.

**Comment by shashwathi** [comment]
Hi @ericpromislow,

Thank you for filing this issue. Closing this in favor of the [PR](https://github.com/cloudfoundry-incubator/routing-release/pull/31).

Regards
Shash
