### ISSUE TITLE
Move to the cloudfoundry GitHub org

### ISSUE THREAD

**Issue by wendorf** [cloudfoundry-incubator/routing-release#57]
That was kinda confusing, but I'm glad I found you!

**Comment by shalako** [comment]
Hi @wendorf We're looking forward to moving this repo from an incubating project to an active one. At that point we can move the repo to the cloudfoundry org.

**Comment by shalako** [comment]
@wendorf Until then, how would recommend the repo could be more discoverable?

**Comment by wendorf** [comment]
Without adding a placeholder repo at cloudfoundry/routing-release with a link the README.md, I'm not sure there's much more to do. I suppose I'm just looking forward to seeing it graduate from the incubator.

(FYI The routing release seems fantastic. I'd graduate it today if I had my druthers! 🎉 )
