### ISSUE TITLE
Unused blob

### ISSUE THREAD

**Issue by robdimsdale** [cloudfoundry-incubator/routing-release#60]
`cf-cli/cf-linux-amd64.tgz` is unused as of c895216de9c103eb577bb56bcc2161e3a9c8049d but it was not removed from the blobs file.

https://github.com/cloudfoundry-incubator/routing-release/blob/release-candidate/config/blobs.yml#L10-L13

**Comment by shashwathi** [comment]
@robdimsdale 

Thank you for raising this issue. It has been fixed.
To prevent this future, I will add a job in CI to test for unused blobs. 

Regards
Shash

**Comment by swetharepakula** [comment]
Closing issue
