### ISSUE TITLE
[Feature Request] allow the route-registrar to be stopped on drain

### ISSUE THREAD

**Issue by malmanzor** [cloudfoundry-incubator/routing-release#68]
## Issue

Route-registrar cannot be shutdown on drain.

## Context

In my bosh release I have two jobs, my application and the route-registrar. The application job has a drain script that calls into the application to prepare it for shutdown. The problem is that the drain process will not complete as long as their are active users accessing the app running on the vm. I would like a way of configuring route-registrar to unregister the route on drain or suggestions about other ways of avoiding this problem.

## Steps to Reproduce

1. Have a job with a drain script that will not terminate while there are active requests to the job
2. Have a route-registrar job that will register the route with the go router.
3. Restart the bosh vm
4. Access to the vm through the registered route is still available while drain is run. New requests keep coming in and the drain script cannot complete. 

## Expected result

I would like a way of unregistering the route on drain so that the application becomes inaccessible through the go router. Or if that is not feasible for some reason a suggestion of other ways I can remove the route.

## Current result

The drain script does not complete since the route is still active.

## Possible Fix

To make sure this was my problem I implemented an optional drain script for route-registrar

https://github.com/malmanzor/routing-release/tree/optional-drain

I can create a PR if my solution is acceptable.

Thank you!

**Comment by shalako** [comment]
Hello @malmanzor 

Have you tried configuring a healthcheck script for your app? I believe your use case is what this was designed for. If you have your healthcheck exit with an error with some drain period before ht app exits, then route for the app will be removed at the beginning of the drain, preventing new connections from being established.

https://github.com/cloudfoundry/route-registrar#health-check

Example manifest configuration: https://github.com/cloudfoundry-incubator/routing-release/blob/develop/jobs/route_registrar/spec#L77-L80

**Comment by malmanzor** [comment]
Thanks @shalako 

I'll give the healthcheck a try.

**Comment by malmanzor** [comment]
The health check worked. I'll close the issue.

Thanks
