### ISSUE TITLE
`X-Cf-App-Instance` header can not be used on DEA applications.

### ISSUE THREAD

**Issue by liuweichu** [cloudfoundry-incubator/routing-release#69]
Thanks for submitting an issue to `routing-release`. We are always trying to improve! To help us, please fill out the following template.

## Issue
`X-Cf-App-Instance` header can not be used on DEA applications.

As a feature introduced in [0.139.0](https://github.com/cloudfoundry-incubator/routing-release/releases/tag/0.139.0) [(ticket)](https://www.pivotaltracker.com/story/show/129122189), it is said that developer can use `X-Cf-App-Instance` to specify a certain backend. We've just upgraded our deployment to cf-release 246 but found that this feature only works on Diego applications.

Our deployment contains both DEA and Diego, so this confused us. I'm not sure the "doesn't work on DEA app" part is a bug or a feature. But since there are many more CF deployments other than PCF, which could be probably still running DEA, this behavior could really confuse users.

## Context

[provide more detailed introduction]

## Steps to Reproduce

1. Push an application to CF (> v245), **app should be host on a DEA**.
2. Follow the [DOC-1](https://github.com/cloudfoundry/docs-dev-guide/blob/master/deploy-apps/routes-domains.html.md.erb) or [DOC-2](https://github.com/cloudfoundry/gorouter/blob/master/README.md), curl with `-H "X-Cf-App-Instance: APP_GUID:APP_INDEX"`

## Expected result

Request should reach APP:APP_INDEX, then correct result returned to developer.

## Current result

Get a 404 `Not Found: Requested route ('app_url') does not exist.`

## Possible Fix

1. Add support for this feature on DEA application.
2. If it is decided that DEA application should not support such feature, this should be documented in the both docs mentioned above.

## `name of issue` Output Results

[if relevant, include a screenshot]

**Comment by liuweichu** [comment]
By the way, we only tested on cf-release v246. If this is already fixed somehow, please tell us.

**Comment by shalako** [comment]
DEAs are considered deprecated and will be EOL in May 2017 (less than two months from now). Most new features in CF support Diego only.

Here's the post to cf-dev last November announcing the start of the six-month timeline for EOL for DEA:
http://cf-dev.70369.x6.nabble.com/cf-dev-Cloud-Foundry-Diego-v1-0-0-released-starting-EOL-schedule-for-DEAs-td6169.html

We will consider updating documentation for the feature to indicate only Diego is supported.
