### ISSUE TITLE
curl with `X-Cf-App-Instance` header but non-corresponding `Host` header would cause panic.

### ISSUE THREAD

**Issue by liuweichu** [cloudfoundry-incubator/routing-release#70]
## Issue

curl with `X-Cf-App-Instance` header but non-corresponding `Host` header would cause panic.

This is reproduced on cf-release v246 which delivered with routing-release v0.141.0

## Context

Seems gorouter doesn't validate the Host header when `X-Cf-App-Instance` is provided in the header.

## Steps to Reproduce

`curl <gorouter_ip>:<gorouter_port> -H "X-CF-APP-INSTANCE: APP_GUID:APP_INDEX" -H "Host: A_WRONG_URL"`

If `APP_GUID:APP_INDEX` is valid, any non-bind-to-the-app `Host` will trigger the panic.
If `APP_GUID:APP_INDEX` is invalid, any non-exist-route `Host` will trigger the panic.

## Expected result

gorouter should not panic. Instead, it should return a 404.

## Current result

gorouter panics.

## Possible Fix

The validation of `Host` should be performed despite whether `X-CF-APP-INSTANCE` is set or not

## `name of issue` Output Results

[if relevant, include a screenshot]

**Comment by shalako** [comment]
@liuweichu This looks like a bug we should fix. Prioritizing for engineering.

**Comment by abbyachau** [comment]
Hi @liuweichu, we've implemented and validated a fix for this issue. Currently it is in RC and it will be included in the next CF release. Thanks!
