### ISSUE TITLE
Documentation for surgical routing is wrong

### ISSUE THREAD

**Issue by jkugler** [cloudfoundry-incubator/routing-release#73]
## Issue

Doc implies APP_INDEX starts at 1, actually starts at 0.

## Context

See http://docs.cloudfoundry.org/devguide/deploy-apps/routes-domains.html#surgical-routing

## Steps to Reproduce

Doc says:

> APP_INDEX, for example 1, 2, or 3, is an identifier for a particular app instance. Use the CLI command cf app APP-NAME to get statistics on each instance of a particular app.

## Expected result

Trying to use an APP_INDEX of (number of instances), e.g. APP_INDEX 10 with 10 instances produces an error.  APP_INDEX goes from zero to (number of instances -1). In fact, `cf app <app name>` which the doc references even show the app count going from 0 on up.

## Current result

Doc is wrong (or implies incorrect information)

## Possible Fix

Fix docs

**Comment by abbyachau** [comment]
Hi @jkugler, thanks for submitting this. We've made a pull request to the documentation to update this page as suggested.

**Comment by shashwathi** [comment]
Closing this issue since document is updated with starting index `0`.

Regards
Shash
