### ISSUE TITLE
Add support for connecting to Routing API DB over TLS

### ISSUE THREAD

**Issue by jmprice** [cloudfoundry-incubator/routing-release#79]
We have a few environments which have strict security policies in place which only allow secure database connections regardless of the data classification or even if the data itself is encrypted.

A recent commit for the UAA release has enabled TLS connections for the UAA DB.
https://www.pivotaltracker.com/n/projects/997278/stories/145563953

Jon Price
Intel Corp

**Comment by shalako** [comment]
Hello @jmprice Thank you reaching out. Although we can't provide a timeline for delivery of this feature, we will keep the issue open. 

@shashwathi Would the eng team take a PR for this?

**Comment by shashwathi** [comment]
@jmprice : 

Yes, PR would be great. Something to keep in mind, we currently support postgres and mysql as the backends for routing API so this change should be done with for both these backends.

Regards
Shash

**Comment by ljfranklin** [comment]
For reference, CAPI team has a similar story in flight to support SSL to MySQL and Postgres CCDB instances: https://www.pivotaltracker.com/story/show/132950039

**Comment by amhuber** [comment]
Any progress on getting this implemented?

**Comment by shalako** [comment]
prioritized for engineering review

**Comment by aaronshurley** [comment]
This was delivered in [v0.166.0](https://github.com/cloudfoundry-incubator/routing-release/releases/tag/0.166.0). Please let us know if this doesn't address your needs.
