### ISSUE TITLE
Configure router for in isolation segment on bosh v1

### ISSUE THREAD

**Issue by ngocvanho** [cloudfoundry-incubator/routing-release#84]
Thanks for submitting an issue to `routing-release`. We are always trying to improve! To help us, please fill out the following template.

## Issue
According to guideline for creating Routing Isolation Segment 
Ref : https://docs.cloudfoundry.org/adminguide/routing-is.html

it is neccessary to config different network/subnet and router for each isolation segment.
This can be done by using cloud-config.
I also learn that all deployments must be converted to use new format if needed to use cloud config.
https://bosh.io/docs/cloud-config.html

But my current deployment uses old format (v1)
Is it possible to configure routers for isolation segments by specifying information directly to  deployment manifest v1?

[provide quick introduction so this issue can be triaged]

## Context

[provide more detailed introduction]

## Steps to Reproduce

[ordered list the process to finding and recreating the issue, example below]

## Expected result

[describe what you would expect to have resulted from this process]

## Current result

[describe what you you currently experience from this process, and thereby explain the bug]

## Possible Fix

[not obligatory, but suggest fixes or reasons for the bug]

## `name of issue` Output Results

[if relevant, include a screenshot]

**Comment by aaronshurley** [comment]
Hello @ngocvanho,

Yes, it is possible to configure routers for isolation segments in bosh v1 format. You can configure the desired values directly in the v1 manifest or create a stub with these properties if using a manifest generation script.

Please let us know if you encounter any issues.

Aaron

**Comment by ngocvanho** [comment]
[cf.txt](https://github.com/cloudfoundry-incubator/routing-release/files/1266937/cf.txt)
[diego.txt](https://github.com/cloudfoundry-incubator/routing-release/files/1266936/diego.txt)

Hi @aaronshurley,
I used bosh-lite to deployment cf-release and diego-release. I have tried to deployed bosh-deployment and cf-deployment but it is unsuccessfully.
In diego.yml file, i created 2 isolation segments: segment1 on cell_z1, segment2 on cell_z2.
In cf.yml file, i started router_z2 instance and configure the router_z2 to routing for segment1. Current, i don't know when app execute on segment1, it  will be routed by the router_z1 or router_z2? 
I attach cf.yml and diego.yml file.

**Comment by Nino-K** [comment]
@ngocvanho sorry for the late response. We highly recommend using cf-deployment, including for isolation segment features, for which [some ops-files and scripts are available](https://github.com/cloudfoundry/cf-deployment/search?utf8=%E2%9C%93&q=isolation&type=).

If you are having trouble using cf-deployment, feel free to ask questions on the CF-dev mailing list or to [open up an issue with the cf deployment project](https://github.com/cloudfoundry/cf-deployment/issues).

Thanks,
@rosenhouse & Nino-K
