### ISSUE TITLE
Use json file extension instead of yml

### ISSUE THREAD

**Issue by enocom** [cloudfoundry-incubator/routing-release#86]
The route registrar depends on [registrar_settings.yml.erb](https://github.com/cloudfoundry-incubator/routing-release/blob/develop/jobs/route_registrar/templates/registrar_settings.yml.erb). While I know that YAML is a superset of JSON, the internals of the template specifically use JSON. Why not just name the file with a `json` extension?

**Comment by aaronshurley** [comment]
Just to provide an update, we moved forward with this request and the commit is currently going through our pipeline. Feel free to track the story mentioned above.

**Comment by aaronshurley** [comment]
This commit was included in [v0.167.0](https://github.com/cloudfoundry-incubator/routing-release/releases/tag/0.167.0)
