### ISSUE TITLE
Expose registration_interval as link

### ISSUE THREAD

**Issue by fhanik** [cloudfoundry-incubator/routing-release#88]
The identity project is implementing bbr for [uaa-release](https://github.com/cloudfoundry/uaa-release/)

In the scenario where a restore takes place the following sequence happens

1. bbr pre-restore-lock -> shuts down the uaa process
2. [wait for the route registrar to remove the route](https://github.com/cloudfoundry/uaa-release/blob/771433cae7393c28f911541814e38da6fe065274/jobs/uaa/templates/bbr/pre-restore-lock.sh.erb#L4-L6)
3. restore happens
4. bbr post-restore-unlock -> starts the UAA process
5. [wait for the route registrar to add the route](https://github.com/cloudfoundry/uaa-release/blob/771433cae7393c28f911541814e38da6fe065274/jobs/uaa/templates/bbr/post-restore-unlock.sh.erb#L8)

The clear flaw in this approach is that if the `registration_interval` in the manifest changes these scripts are still hard coded. 

We are wondering if the [`registration_interval`](https://github.com/cloudfoundry/cf-deployment/blob/master/cf-deployment.yml#L480-L483) property can be
1. exposed as a link so that the colocated UAA job can consume it
2. document possible time values. documentation mentions `s` for seconds, but not any other time units.

**Comment by shalako** [comment]
Prioritizing for eng review

**Comment by shalako** [comment]
Exposing a link could be a challenge, as the route-registrar colocated with each job will expose the same link by default and consumers will not be able to differentiate between them; the deploy will fail.

How to ensure that each route-registrar job is configured to provide a different link alias, and consumers configured to use the alias?

**Comment by shalako** [comment]
Prioritizing for eng review

**Comment by shalako** [comment]
@fhanik We'd like to schedule a chat to better understand what you're trying to achieve and whether predicting the time of route registration/unregistration is the best solution. I'll send an invite.

**Comment by rosenhouse** [comment]
@shalako @fhanik @aaronshurley sounds like y'all chatted already.  can this issue be closed?

**Comment by shalako** [comment]
Yes, this can be closed.
