### ISSUE TITLE
Force client Cert validation.

### ISSUE THREAD

**Issue by mandar14** [cloudfoundry-incubator/routing-release#91]
I'm using cloud foundry v276, and want to implement  forced client cert validation for all request.
I can see similar properties are added in last few days on develop branch, how can I incorporate such functionality in CF v276.

In addition to this can someone through light  on XFCC property and how its work.
Considering I Want my router to validate Client ssl certificate(for all request) but, application behind router can be simple hello-world app and has nothing to do with  with client cert, is it necessary to set this XFCC property at all.

Thanks,
Mandar

**Comment by charleshansen** [comment]
Hi @mandar14 to get the new feature in cf 276, you will need to manually update your routing release to [0.167.0](https://bosh.io/releases/github.com/cloudfoundry-incubator/cf-routing-release?version=0.167.0) (this is kinda tricky if you haven't done it before)

The XFCC property is a header that the gorouter attaches when it terminates mTLS. The header contains the client cert used in the mTLS. If an application wants to validate the client certificate, they can pull it out of the XFCC header and validate it themselves. Some applications may respond with a 401/403 if a valid XFCC header is not present. Most applications probably ignore XFCC altogether.

**Comment by mandar14** [comment]
Hi @charleshansen , The  property I'm looking at is client _cert_validation (want to set it to required)which is not yet part of  0.167.0
As you said above,  XFCC is header attached by gorouter when it terminates mTLS, does this mean go router cross check / validate client cert and reject or approve request from client??  How to set this? 
My app is simple and don't have logic of authentication, can router be force to do that??

On other hand now  I m thinking , If router start evaluating request and on of my services broker is application, as all call  come through router  does it going to brokedown  brokers functionality on `cf bind` or `cf cs`  call if valid certs are not provided🤔

Thanks

**Comment by charleshansen** [comment]
Ah, if it isn't in 0.167.0 yet, you need to check out the `develop` or `release-candidate` branch of routing release and run `bosh create-release` yourself. You can then upload that directly.

The router will validate the client cert if you set `client_cert_validation` to `request` and it will also require the certificate if you set it to `require`. The XFCC header is more to do very specific client validation (maybe an app requires more validation than your cloudfoundry requires as a whole). You can offload the validation to the gorouter for most apps.

As you say, XFCC could be used for apps that act as services, to do multi-tenant security.

**Comment by shalako** [comment]
0.168.0 includes support for a new property `router.client_cert_validation` that can be used to enforce mutual authentication between client and Gorouter. This does not support authorization; if you'd like to have your application do authorization, you can have Gorouter forward the client certificate to your application.
